### ISSUE TITLE
configuration files on other browsers than Chrome displayed as single line.

### ISSUE THREAD

**Issue by gmkey** [Woersty/LoxBerry-Plugin-DNSmasq#5] opened 2018-12-04 15:04 UTC
On my machine, (MacBook Air), all the configuration files for the DNSmasq plugin are displayed as single line, with safari (12.0.1) and Firefox (63.0.3).  (I've noticed this behaviour earlier but didn't write down the versions).

in firefox the errors are:
Source map error: request failed with status 404
Resource URL: http://<ip>/system/scripts/jquery/jquery.mobile-1.4.5.min.js
Source Map URL: jquery.mobile-1.4.5.min.map
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://c47372a4-4b4f-1045-9b1d-54ad39bb11fa/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map

in safari the errors are:
Failed to load resource: the server responded with a status of 404 (Not Found) http://<ip>/system/scripts/jquery/jquery.mobile-1.4.5.min.map

**Comment by Woersty** [comment] 2018-12-04 21:29
Duplicate of https://github.com/Woersty/LoxBerry-Plugin-DNSmasq/issues/1

The other errors are Loxberry Core errors - not plugin errors.
Report here=> https://github.com/mschlenstedt/Loxberry/issues/

**Closed as completed by Woersty** 2018-12-04 21:29 UTC

**Comment by Woersty** [comment] 2018-12-04 23:06
Please update to Pre-Release 2018.12.05.1 using Autoupdate or manual install https://github.com/Woersty/LoxBerry-Plugin-DNSmasq/archive/v2018.12.05.1.zip

**Comment by gmkey** [comment] 2018-12-06 10:37
I have to disagree. I is a issue with the dnsmasq.html page. It uses a wrong stylesheet for textareas that google chrome is kind to, but safari and firefox aren't. I've created a pull-request
